Repository canonical/dotrun, pull requests merged in 2020-03, with the labels that each got.

#19 v1.1.0: Re-enable strict mode
  CHANGES.txt
  README.md
  scripts/test-snap-in-multipass
  snap/snapcraft.yaml
  src/canonicalwebteam/__init__.py
  src/canonicalwebteam/dotrun/__init__.py
  src/canonicalwebteam/dotrun/file_helpers.py
  src/canonicalwebteam/dotrun/models.py
  src/lib.c
  src/setup.py
  tests/fixtures/python-project/another.py
  tests/test_python_project.py
Labels: Review: Code +1, Review: QA +1

#20 MacOS instructions; install black, flake8, ipdb to snap itself
  CHANGES.txt
  README.md
  snap/snapcraft.yaml
  src/canonicalwebteam/dotrun/models.py
  src/setup.py
Labels: Review: Code +1, Review: QA +1

#21 Use $SNAPCRAFT_PART_INSTALL
  snap/snapcraft.yaml
Labels: Review: Code needed, Review: QA needed

#22 Mention Talisker version requirements in README
  README.md
Labels: Review: Code +1

#23 Include flask-base in readme
  README.md
Labels: Review: Code +1, Review: QA +1

#27 v1.1.5: Access to ~/.npmrc
  CHANGES.txt
  README.md
  scripts/test-snap-in-multipass
  snap/snapcraft.yaml
  src/canonicalwebteam/dotrun/__init__.py
  src/canonicalwebteam/dotrun/models.py
  tests/fixtures/yarn-project/package.blueprint.json
  tests/fixtures/yarn-project/package.json.backup
  tests/test_python_project.py
  tests/test_yarn_project.py
Labels: Review: Code +1, Review: QA +1

#30 Add gettext dependency, for django-admin makemessages
  CHANGES.txt
  snap/snapcraft.yaml
Labels: Review: Code +1

#31 Add snapcraftctl build
  snap/snapcraft.yaml
Labels: Review: Code +1, Review: QA +1
